version: '3.8'

services:
  firefly-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VITE_FIREFLY_API_URL: ${VITE_FIREFLY_API_URL}
        VITE_FIREFLY_TOKEN: ${VITE_FIREFLY_TOKEN}
        VITE_FIREFLY_URL: ${VITE_FIREFLY_URL}
        VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
        VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
        VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
        VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
        VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
        VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
    # Expose port 3000 to Coolify/Traefik explicitly
    expose:
      - "3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    #healthcheck:
    #  test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health" ]
    #  interval: 30s
    #  timeout: 3s
    #  retries: 3
    #  start_period: 5s
